### ISSUE TITLE
Add <encodeIfEmpty> to mappings containing constant client properties

### ISSUE THREAD

**Issue by ridethepenguin** [ridethepenguin/hale#15]
If a XML attribute is mapped to in HALE without using information from the source (e.g. using Assign) the corresponding `<AttributeMapping>` should always include `<encodeIfEmpty>true</encodeIfEmpty>`, otherwise the XML attribute may not appear.

Q: what to do when the attribute is populated from the source? The element (if it has no value itself) should probably only be there if at least one of its attributes has a non-null value.

**Comment by ridethepenguin** [comment]
OK, I found out why the element is encoded sometimes, even if only client properties are present, and some other times it's not: App-Schema treats the `xlink:href` attribute specially and considers that an element **does** have content if its `xlink:href` attribute does. The same does not hold true for any other attribute type.

**Comment by ridethepenguin** [comment]
However, on second thought, I'm not 100% sure we should just set `<encodeIfEmpty>true</encodeIfEmpty>` so lightly. Let's say we have an element that may contain other nested elements, but in some cases its content is `null`; let's also suppose the element has attributes that are being populated with constant values. If we set `<encodeIfEmpty>true</encodeIfEmpty>`, the element will always be encoded, even when it has no content, which is probably not what the user wants.

So, this brings me to conclude also that to decide whether or not `<encodeIfEmpty>true</encodeIfEmpty>` should be added, **the content of its child elements** should be taken into account. This quite complicates things.

**Comment by stempler** [comment]
I don't agree for the special case of using a mapping function that does not depend on the source (like Assign) to provide a value for an XML attribute (= child property). This is always executed in HALE - if you do not want a value in certain cases, you need something that depends on the source. That attribute should always be present, regardless if there are children to the element or not (It being an XML attribute instead of an element does not mean it cannot carry information on its own). And without the encodeIfEmpty, both the element and the attribute will not appear. Except if there is a value for the element, or the element has child elements - but you can also have structures where the only content of an element are supposed to be attributes.

A prominent example in INSPIRE are `nilReason` attributes. They generally should be present if you don't have an element value (or child elements).
I admit the way it is handled in HALE is not optimal either, because with an Assignment you have a nilReason even if you have a value, but having the nilReason disappear because there is no value for the element is counterproductive.

Regarding the matter of more complicated uses cases - there would also be the possibility to store additional (app-schema specific) configuration in a mapping cell via an annotation (see `Cell.addAnnotation`). This mechanism could be used to control if a mapping implies encodeIfEmpty on a parent or not. But this, having only the two options of using encodeIfEmpty or not, is probably not enough flexibility for many cases, where the desired encoding depends on source or target.

**Comment by ridethepenguin** [comment]
I see your point and I think it probably makes more sense to have the generated mapping reproduce as closely as possible HALE's behavior, which means, if I understand you correctly, that an element with a constant attribute is always encoded, right? This simplifies things a lot, as I just need to add `<encodeIfEmpty>true</encodeIfEmpty>` if I see a constant value set in a client property.

Regarding cell annotations - that sounds really cool! :smile: Can they be managed from the UI?

**Comment by stempler** [comment]
> Regarding cell annotations - that sounds really cool! :smile: Can they be managed from the UI?

Like complex `Value`s that you can use for representing complex configuration in XML, for cell annotations you define in a similar way how they are stored and restored to/from XML. This mechanism was put in place some time ago, but so far only the simpler mechanism of cell documentation has been used.

Editing cell annotations could be done similar to the cell notes that are available right now in the properties view, when you select a cell. The UI would have to be specific to the annotation, but apart from that the class `NotesCellSection` could serve as an example.

**Comment by ridethepenguin** [comment]
Implemented in [this PR](https://github.com/igd-geo/hale/pull/14).
